all: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16

1: task1.c
	gcc task1.c -o task1 -Wall

2: task2.c
	gcc task2.c -o task2 -Wall

3: task3a.c task3b.c task3c.c
	gcc task3a.c -o task3a -Wall
	gcc task3b.c -o task3b -Wall -lm
	gcc task3c.c -o task3c -Wall -lm

4:	task4.c
	gcc task4.c -o task4 -Wall

5:	task5.c
	gcc task5.c -o task5 -Wall -lm

6:	task6.c
	gcc task6.c -o task6 -Wall

7:	task7.c
	gcc task7.c -o task7 -Wall -lm

8:	task8.c
	gcc task8.c -o task8 -Wall

9:	task9.c
	gcc task9.c -o task9 -Wall

10:	task10.c
	gcc task10.c -o task10 -Wall

11:	task11.c
	gcc task11.c -o task11 -Wall

12:	task12.c
	gcc task12.c -o task12 -Wall -lm

13:	task13.c
	gcc task13.c -o task13 -Wall

14:	task14.c
	gcc task14.c -o task14 -Wall

15:	task15.c
	gcc task15.c -o task15 -Wall

16:	task16.c
	gcc task16.c -o task16 -Wall

clean:
	rm task1
	rm task2
	rm task3a
	rm task3b
	rm task3c
	rm task4
	rm task5
	rm task6
	rm task7
	rm task8
	rm task9
	rm task10
	rm task11
	rm task12
	rm task13
	rm task14
	rm task15
	rm task16
